---
title: "CBC cleaning"
author: "Francis Joyce"
date: "2020-12-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(naniar)
library(knitr)
library(kableExtra)
library(here)
```

Download data from here: https://netapp.audubon.org/cbcobservation/historical/resultsbycount.aspx#

Use count code NIPI

Start year = 115 (2014) (but since NIPI count is in Jan, 2014 winter is really 2015 calendar year)
can do this with code after importingEnd year = 121 (2020)

CSV, sort Taxonomic


##MANUAL CLEANING

Then, delete non-species count top rows.

ALso delete the rows below for participants...

```{r}
NIPI_cbc <- read_csv(here("data/NIPI-2015-2021_pre-cleaned.csv"))

```


```{r}
#preview data frame
NIPI_cbc %>%
  head() %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")

```

```{r}
NIPI_cbc <- NIPI_cbc %>% 
  rename(species = COM_NAME, 
         count_year = CountYear, 
         how_many_cw = how_manyCW,
         number_by_party_hours = NumberByPartyHours,
         flags = Flags
        )

```



```{r}
#this just pulls out the values in the species columnn for the first row
NIPI_cbc %>% 
  filter(row_number() == 1) %>% 
  pull(species)

```

```{r}
# create new variable for scientific name and make species just common name
NIPI_cbc <- NIPI_cbc %>%
  mutate(species_latin = str_extract(species, "(?<=\\[).+?(?=\\])"),
         species = word(species, start = 1, sep = fixed('\n[')))

```


```{r}
#I think this is an artifact from Sharleen's code...
#CRMO_cbc %>% 
  #filter(row_number() == 15133) %>% 
  #pull(count_year)
```

```{r}
# again, code from Sharleen W that I idn't actually use

count_participant_meta_data <- NIPI_cbc %>%
  distinct(participant_info = count_year) %>%
  mutate(year = word(participant_info)) %>%
  mutate(number_of_participants = str_extract(
    participant_info, "(?<=Participants:\\s).+?(?=\\s#)")) %>%  # Gets everything between "Participants: " and " #"
  mutate(species_reported = str_extract(
    participant_info, "(?<=Reported:\\s).+?(?=\\nTotal)")) %>%  # Gets everything between "Reported: " and "Total"
  mutate(total_hours = str_extract(
    participant_info, "(?<=Hrs\\.:\\s).*$"))  # Gets everything after "Hrs.: "
# This regex is different because it goes until the end of the string:
# https://forum.sublimetext.com/t/regex-match-everything-after-this-word/20764

count_participant_meta_data %>%
  head(n = 3) %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")
```


```{r}
NIPI_cbc <- NIPI_cbc %>%
  rename(participant_info = count_year,
         how_many_counted = how_many_cw) %>%
  mutate(year = as.integer(word(participant_info)),  # We will keep year and total_hours
         total_hours = as.double(
           str_extract(
             participant_info, "(?<=Hrs\\.:\\s).*$")))
```

```{r}
#select only the columns needed by the shiny app
NIPI_cbc <- NIPI_cbc %>%
  select(year, species, species_latin, how_many_counted, total_hours)
```


```{r}
#remove cw records
NIPI_cbc <- NIPI_cbc %>%
  mutate(how_many_counted = ifelse(how_many_counted == "cw", NA, how_many_counted),
         how_many_counted = as.integer(how_many_counted))
```

```{r}
#filter out generic IDs?
NIPI_cbc %>%
filter(str_detect(species, "sp\\.")) %>%
distinct(species)
```


```{r}
NIPI_cbc <- NIPI_cbc %>%
  filter(!(str_detect(species, "sp\\.")))
```

```{r}
#replace NAs with 0s
NIPI_cbc <- NIPI_cbc %>%
  mutate(how_many_counted = replace_na(how_many_counted, 0),
         how_many_counted_by_hour = as.double(how_many_counted) / total_hours,
         year = as.integer(year + 1))
```

```{r}
NIPI_cbc %>%
  head() %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")
```

Move this file manually to the root directory

```{r}
write_csv(NIPI_cbc, "NIPI-CBC-2021-cleaned.csv")
```


Clean up and add 2021 data
```{r}
## Didn't actually end up using/needing this chunk, because I just waited until 2021 data was incorporated into the historical database instead of "current year"

NIPI_cbc_2021 <- read_csv(here("data/NIPI-CBC-2021.csv"))


#make the columns & column order match the dataset for previous years
NIPI_cbc_2021 <- NIPI_cbc_2021 %>% 
  select(c(-Flags, -Editorial_Comments)) %>%
  rename(species= Species, how_many_counted = Number, how_many_counted_by_hour = Number_Per_Party_Hrs) %>% 
  mutate(year= 2021) %>% 
  relocate(year) %>% 
  mutate(total_hours= 67.10) %>% 
  relocate(total_hours, .before = how_many_counted_by_hour)
  
#get the list of unique common + Latin names for species that have been recorded
NIPI_species <- NIPI_cbc %>% 
  select(c(species,species_latin)) %>% 
  unique()

NIPI_cbc_2021 <- left_join(NIPI_cbc_2021, NIPI_species)


```




